[package]
name = "rust_robotics_algo"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8"
nalgebra = "0.30"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
sprs = "0.11"

[dependencies.clarabel]
version = "0.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ort = { version = "2.0.0-rc.12", default-features = false, features = ["std", "ndarray", "load-dynamic", "api-20", "alternative-backend"] }
libloading = "0.8"

[target.'cfg(target_arch = "wasm32")'.dependencies.clarabel]
version = "0.9"
features = ["wasm"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.85"
ort = { version = "2.0.0-rc.12", default-features = false, features = ["std", "ndarray", "api-20", "alternative-backend"] }
ort-web = "0.2.1"
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.58"

[features]
default = []

[package.metadata.docs.rs]
all-features = true
