#!/usr/bin/env python3
"""One-shot #33 development ablation; never changes production or selects a winner.

Baseline must be generated by the unchanged diagnostic runner in this checkout.
The test-local 4.0 override and reader metadata expectation are restored even on
failure. No outcome retries, confirmation data, new thresholds or tuning.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys

BASE = "d724c517c27b182145d4054a66d3937563381dfd"
TEST = Path("rust_robotics_train/tests/ppo_balancing_diagnostics.rs")
READER = Path("scripts/diagnose_ppo_balancing.py")
BLOBS = {
    TEST: "db3d8b8c1b892c33829e17654c4388780d39b55d",
    READER: "3122885ddaa74a6409e57f3e6450d6639e085863",
}


def sha(data):
    return hashlib.sha256(data).hexdigest()


def blob(data):
    return hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()


def replace_once(text, old, new):
    assert text.count(old) == 1, ("nonunique patch anchor", old)
    return text.replace(old, new)


def table(path):
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def compare(baseline, candidate):
    old_report = json.loads((baseline / "results.json").read_text())
    new_report = json.loads((candidate / "results.json").read_text())
    assert old_report["completed"] and new_report["completed"]
    assert old_report["commit"] == new_report["commit"], "same source checkout required"
    assert old_report["rustc"] == new_report["rustc"], "same compiler required"
    old_config = (baseline / "config.txt").read_text()
    assert old_config.count("action_std: 2.0") == 1
    assert (candidate / "config.txt").read_text() == old_config.replace("action_std: 2.0", "action_std: 4.0"), "only exploration config may differ"
    assert (baseline / "lqr.txt").read_bytes() == (candidate / "lqr.txt").read_bytes()
    for path, digest in old_report["source_sha256"].items():
        if path not in (str(TEST), str(READER)):
            assert new_report["source_sha256"][path] == digest, ("production/source drift", path)
    for root, report in ((baseline, old_report), (candidate, new_report)):
        for relative, digest in report["source_sha256"].items():
            assert sha((root / "sources" / relative).read_bytes()) == digest
        for relative, digest in report["evidence_sha256"].items():
            assert sha((root / relative).read_bytes()) == digest

    # The controllers, initial numeric weights and random episode conditions
    # must be the same. Exclude only the actor's exploration metadata float.
    old_snapshots = {(r["training_seed"], r["updates"], r["kind"]): r["f32_hex"] for r in table(baseline / "snapshots.tsv")}
    for row in table(candidate / "snapshots.tsv"):
        if row["updates"] == "0":
            key = (row["training_seed"], row["updates"], row["kind"])
            old, new = old_snapshots[key], row["f32_hex"]
            if row["kind"] == "actor":
                assert old[:8] == new[:8] and old[16:] == new[16:], "initial actor weights differ"
                assert old[8:16] == "40000000" and new[8:16] == "40800000"
            else:
                assert old == new, "initial critic weights differ"
    for filename in ("episodes.tsv", "traces.tsv"):
        initial_and_controls = lambda rows: [r for r in rows if r["updates"] == "0"]
        assert initial_and_controls(table(baseline / filename)) == initial_and_controls(table(candidate / filename)), "initial/control trajectories differ"

    # Report every checkpoint and all four training-seed units, never the best.
    old_groups = {(g["controller"], g["updates"], g["training_seed"]): g for g in old_report["summary"]["groups"]}
    paired = []
    for new in new_report["summary"]["groups"]:
        if new["controller"] != "ppo":
            continue
        old = old_groups[(new["controller"], new["updates"], new["training_seed"])]
        paired.append({"training_seed": new["training_seed"], "updates": new["updates"],
                       "baseline": old, "candidate": new,
                       "delta_completions": new["endings"]["Timeout"] - old["endings"]["Timeout"],
                       "delta_mean_return": new["mean_return"] - old["mean_return"],
                       "delta_mean_steps": new["mean_steps"] - old["mean_steps"]})
    return {"development_only": True, "statistical_units": 4, "primary_checkpoint": 2048,
            "baseline_action_std": 2.0, "candidate_action_std": 4.0,
            "same_build_and_initial_controls": True, "paired_checkpoints": paired}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    root = args.output.resolve()
    root.mkdir(parents=True, exist_ok=False)
    saved = {path: path.read_bytes() for path in BLOBS}
    report = {"development_only": True, "base": BASE, "commands": []}

    def run(label, command, count=None):
        env = {**os.environ, "CARGO_TERM_COLOR": "never", "PYTHONDONTWRITEBYTECODE": "1"}
        log = root / (label + ".log")
        with log.open("w") as handle:
            completed = subprocess.run(command, env=env, text=True, stdout=handle, stderr=subprocess.STDOUT, timeout=1800)
        output = log.read_text()
        entry = {"label": label, "command": command, "returncode": completed.returncode, "sha256": sha(log.read_bytes())}
        report["commands"].append(entry)
        print(label, completed.returncode, flush=True)
        assert completed.returncode == 0, (label, output[-6000:])
        if count is not None:
            assert f"test result: ok. {count} passed; 0 failed; 0 ignored;" in output

    try:
        report["head"] = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
        subprocess.run(["git", "diff", "--exit-code"], check=True)
        changes = set(subprocess.check_output(["git", "diff", "--name-only", BASE, "HEAD"], text=True).splitlines())
        assert changes == {"scripts/run_ppo_exploration_ablation.py", ".github/workflows/ppo-exploration-ablation.yml"}, changes
        for path, digest in BLOBS.items():
            assert blob(saved[path]) == digest, (path, blob(saved[path]))
        script_copy = root / "run_ppo_exploration_ablation.py"
        script_copy.write_bytes(Path(__file__).read_bytes())
        workflow = Path(".github/workflows/ppo-exploration-ablation.yml")
        (root / workflow.name).write_bytes(workflow.read_bytes())
        # Only the printed and actually constructed test-local config changes.
        text = TEST.read_text()
        start = text.index("fn measure_default_balancing_development_panel()")
        end = text.index("\n#[test]", start)
        endpoint = text[start:end]
        assert endpoint.count("PpoTrainerConfig::default()") == 2
        replacement = "PpoTrainerConfig { action_std: 4.0, ..PpoTrainerConfig::default() }"
        TEST.write_text(text[:start] + endpoint.replace("PpoTrainerConfig::default()", replacement) + text[end:])
        # Keep both independent metadata assertions strict for the candidate.
        TEST.write_text(replace_once(TEST.read_text(), "assert_eq!(shared.policy.action_std, 2.0);", "assert_eq!(shared.policy.action_std, 4.0);"))
        READER.write_text(replace_once(READER.read_text(), "assert values[:2] == (20.0, 2.0)", "assert values[:2] == (20.0, 4.0)"))
        run("format-candidate", ["cargo", "fmt", "--all"])
        changed = set(subprocess.check_output(["git", "diff", "--name-only"], text=True).splitlines())
        assert changed == {str(TEST), str(READER)}, changed
        (root / "candidate.patch").write_text(subprocess.check_output(["git", "diff"], text=True))
        run("candidate-controls", ["cargo", "test", "--locked", "-p", "rust_robotics_train", "--test", "ppo_balancing_diagnostics", "--", "--skip", "measure_default_balancing_development_panel", "--test-threads=1"], 7)
        run("candidate-clippy", ["cargo", "clippy", "--locked", "-p", "rust_robotics_train", "--all-targets", "--", "-D", "warnings"])
        run("candidate-measurements", [sys.executable, str(READER), "--output", str(root / "std4")])
        report["comparison"] = compare(args.baseline.resolve(), root / "std4")
        report["completed"] = True
    except Exception as exc:
        report["error"] = repr(exc)
        raise
    finally:
        for path, data in saved.items():
            path.write_bytes(data)
        restored = subprocess.run(["git", "diff", "--exit-code"], text=True, capture_output=True)
        report["restored_clean"] = restored.returncode == 0
        report["restored_diff"] = restored.stdout
        report["file_sha256"] = {p.name: sha(p.read_bytes()) for p in root.iterdir() if p.is_file() and p.name != "comparison.json"}
        (root / "comparison.json").write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")
        assert report["restored_clean"], "tracked files not restored"


if __name__ == "__main__":
    main()
